version: '3.7'
services:
    postgres:
        image: some-postgis:12 #postgres:12
        restart: always
        environment: 
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=cropio_db
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./cropio_api_structure.sql:/docker-entrypoint-initdb.d/create_tables.sql