version: '3.7'
services:
    cropio_backupper:
        container_name: 'cropiobackupper'
        image: 'cropio/cropio-backupper'
        restart: always
        environment:
          - REDIS_HOST=redis
          - DB_HOST=postgres
          - DB_PORT=5433
          - DB_NAME=cropio
          - DB_USERNAME=postgres
          - DB_PASSWORD=postgres
          - API_TOKEN=secretCropioToken
        depends_on:
          - postgres
          - redis

    postgres:
        container_name: 'postgres'
        image: 'postgis/postgis:12-3.2' #postgres:12
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=cropio_db
          - PGDATA=/var/lib/postgresql/data/pgdata
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '127.0.0.1:5438:5433'
        volumes:
          - postgres-data:/var/lib/postgresql/data
          - postgres-dump:/postgres_dump
          # copy the sql script to create tables
          - cropio_api_structure:/docker-entrypoint-initdb.d/cropio_api_structure.sql

    redis:
        container_name: 'redis'
        restart: always
        image: 'redis:3.2.0'
        ports:
          - '127.0.0.1:6379:6379'
        volumes:
          - 'redisdata:/data'
volumes:
    redisdata:             #
        driver: local
        driver_opts:
          type: 'none'
          o: 'bind'
          device: '/docker_volumes/redis_db'
    postgres-data:         #
        driver: local
        driver_opts:
          type: 'none'
          o: 'bind'
          device: '/docker_volumes/postgres_db'
    postgres-dump:         #
        driver: local
        driver_opts:
          type: 'none'
          o: 'bind'
          device: '/docker_volumes/postgres_dump'
    cropio_api_structure:  #